// widgets/faq-section/faq-section.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ChevronDown } from "lucide-react";
import { SectionHeader } from "@/shared/ui/section-header";
import { cn } from "@/shared/lib/utils";

interface FaqItem {
  question: string;
  answer: string;
}

const faqGroups: { title: string; items: FaqItem[] }[] = [
  {
    title: "Поиск работы: куда обращаться?",
    items: [
      {
        question: "Какую помощь оказывает Центр занятости населения для эффективного трудоустройства?",
        answer:
          "Центр занятости помогает подобрать вакансии с учётом вашего опыта и пожеланий, организует бесплатное обучение и переподготовку, оказывает психологическую поддержку и консультирует по вопросам трудового законодательства.",
      },
    ],
  },
  {
    title: "Постановка на учёт",
    items: [
      {
        question: "Какие документы нужны для регистрации в качестве безработного?",
        answer:
          "Понадобятся паспорт, трудовая книжка (или сведения о трудовой деятельности), справка о среднем заработке за последние три месяца, а также документы об образовании и квалификации.",
      },
    ],
  },
  {
    title: "Выплаты и пособия",
    items: [
      {
        question: "Как получить статус безработного и пособие по безработице?",
        answer:
          "Подайте заявление на портале «Работа России» или обратитесь в ближайший ЦЗН с полным пакетом документов. Решение о признании безработным принимается в течение 11 дней.",
      },
    ],
  },
  {
    title: "Обучение и переподготовка",
    items: [
      {
        question: "Какие курсы и программы обучения доступны бесплатно?",
        answer:
          "Доступны курсы по востребованным профессиям с возможностью получения новой квалификации или повышения разряда. Длительность — от 1 недели до 6 месяцев. Во время обучения выплачивается стипендия.",
      },
    ],
  },
  {
    title: "Поддержка работодателей",
    items: [
      {
        question: "Как разместить вакансию на портале «Работа России»?",
        answer:
          "Зарегистрируйтесь на портале trudvsem.ru, заполните профиль работодателя и создайте вакансию. Публикация бесплатна и занимает несколько минут.",
      },
    ],
  },
];

function FaqAccordion({ item }: { item: FaqItem }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-gray-200">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between gap-4 py-4 text-left"
      >
        <span className="text-sm font-medium text-[#0050AA] hover:text-[#003D82] transition-colors">
          {item.question}
        </span>
        <ChevronDown
          className={cn(
            "h-4 w-4 shrink-0 text-[#0050AA] transition-transform duration-200",
            open && "rotate-180"
          )}
        />
      </button>
      {open && (
        <div className="pb-4 pr-6 text-sm text-[#3A5070] leading-relaxed">
          {item.answer}
        </div>
      )}
    </div>
  );
}

export function FaqSection() {
  return (
    <section className="py-16 md:py-24 bg-white">
      <div className="container">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6 mb-10">
          <h2 className="text-2xl font-bold text-[#0A1628] md:text-3xl lg:text-4xl leading-tight">
            Частые вопросы
          </h2>
          <Link
            href="/faq"
            className="flex items-center gap-1.5 text-sm font-medium text-[#0050AA] hover:text-[#003D82] transition-colors shrink-0"
          >
            Все вопросы
            <ArrowRight className="h-3.5 w-3.5" />
          </Link>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 lg:gap-10">
          {/* Левая колонка — группы вопросов */}
          <div className="lg:col-span-2 space-y-8">
            {faqGroups.map((group) => (
              <div key={group.title}>
                <h3 className="text-base font-semibold text-[#0A1628] mb-2">
                  {group.title}
                </h3>
                <div className="border-t border-gray-200">
                  {group.items.map((item, index) => (
                    <FaqAccordion key={index} item={item} />
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Правая колонка — навигация по категориям */}
          <aside className="lg:col-span-1">
            <div className="rounded-2xl border border-gray-100 bg-white p-6 lg:sticky lg:top-24">
              <h3 className="text-sm font-semibold text-[#0A1628] mb-4">
                Категории вопросов
              </h3>
              <ul className="space-y-3">
                {faqGroups.map((group) => (
                  <li key={group.title}>
                    <a
                      href="#"
                      className="block text-sm text-[#0050AA] hover:text-[#003D82] hover:underline transition-colors leading-snug"
                    >
                      {group.title}
                    </a>
                  </li>
                ))}
              </ul>

              <div className="mt-6 pt-6 border-t border-gray-100">
                <p className="text-sm font-semibold text-[#0A1628] mb-2">
                  Не нашли ответ на свой вопрос?
                </p>
                <p className="text-sm text-[#3A5070] leading-relaxed mb-4">
                  Можете обратиться в электронную приёмную центра «Моя работа»
                </p>
                <Link
                  href="/appeals"
                  className="inline-flex items-center gap-1.5 text-sm font-medium text-[#0050AA] hover:text-[#003D82] transition-colors"
                >
                  Подать обращение
                  <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </section>
  );
}

// components/widgets/FaqSection.vue
<script setup lang="ts">
import { ref } from 'vue'
import { ChevronDown, MessageCircle } from 'lucide-vue-next'
import { cn } from '@/shared/lib/utils'

const activeId = ref<number | null>(null)

const faqs = [
  {
    id: 1,
    question: 'Поиск работы: куда обращаться?',
    answer: 'Вы можете обратиться в любой филиал Центра занятости населения или воспользоваться порталом «Работа России». Наши специалисты помогут подобрать вакансии, соответствующие вашему опыту и квалификации.'
  },
  {
    id: 2,
    question: 'Какую помощь оказывает Центр занятости населения для эффективного трудоустройства?',
    answer: 'Мы предоставляем услуги по профессиональной ориентации, организуем психологическую поддержку, проводим программы переобучения и повышения квалификации, а также помогаем в составлении резюме и подготовке к собеседованиям.'
  }
]

const sidebarLinks = [
  { title: 'Поиск работы', href: '#', active: true },
  { title: 'Как получить статус безработного', href: '#' },
  { title: 'Пособие по безработице', href: '#' },
]

const toggle = (id: number) => {
  activeId.value = activeId.value === id ? null : id
}
</script>

<template>
  <section class="py-16 md:py-24 bg-white">
    <div class="container">
      <div class="flex items-baseline justify-between mb-12 border-b border-gray-100 pb-4">
        <h2 class="text-2xl md:text-3xl font-bold text-[#0A1628]">Частые вопросы</h2>
        <NuxtLink to="/faq" class="text-sm font-medium text-[#0050AA] hover:underline">
          Все вопросы
        </NuxtLink>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <!-- Аккордеон вопросов -->
        <div class="lg:col-span-8 space-y-4">
          <div 
            v-for="faq in faqs" 
            :key="faq.id"
            class="border-b border-gray-100 last:border-0 pb-4"
          >
            <button
              @click="toggle(faq.id)"
              class="flex w-full items-center justify-between py-4 text-left group transition-all"
            >
              <span 
                class="text-lg font-medium text-[#0050AA] group-hover:text-[#003D82] transition-colors leading-snug pr-8"
              >
                {{ faq.question }}
              </span>
              <ChevronDown 
                :class="cn(
                  'h-5 w-5 text-[#7A96B4] transition-transform duration-300 shrink-0',
                  activeId === faq.id && 'rotate-180'
                )" 
              />
            </button>
            <div 
              v-if="activeId === faq.id"
              class="overflow-hidden animate-in fade-in slide-in-from-top-2 duration-300"
            >
              <p class="pb-4 text-[#3A5070] leading-relaxed">
                {{ faq.answer }}
              </p>
            </div>
          </div>
        </div>

        <!-- Правый сайдбар -->
        <div class="lg:col-span-4 lg:border-l lg:border-gray-100 lg:pl-12">
          <nav class="space-y-6">
            <div class="space-y-4">
              <NuxtLink
                v-for="link in sidebarLinks"
                :key="link.title"
                :to="link.href"
                :class="cn(
                  'block text-base transition-colors hover:text-[#0050AA]',
                  link.active ? 'text-[#0050AA] font-semibold border-l-2 border-[#0050AA] pl-4 -ml-[49px] bg-blue-50/50 py-1' : 'text-[#3A5070]'
                )"
              >
                {{ link.title }}
              </NuxtLink>
            </div>

            <div class="pt-8 border-t border-gray-100">
              <p class="text-sm font-semibold text-[#0A1628] mb-2">Не нашли ответа на свой вопрос?</p>
              <p class="text-sm text-[#3A5070] mb-4">Можете обратиться в электронную приемную центра "Моя работа"</p>
              <button class="flex items-center gap-2 text-sm font-bold text-[#0050AA] hover:text-[#003D82] transition-colors group">
                <MessageCircle class="h-4 w-4" />
                Задать свой вопрос
                <span class="block h-px w-0 bg-[#0050AA] transition-all group-hover:w-full" />
              </button>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </section>
</template>
