// widgets/projects-section/projects-section.tsx
"use client";

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { ProjectCard } from "@/entities/project-card/project-card";
import { SectionHeader } from "@/shared/ui/section-header";
import { Button } from "@/shared/ui/button";
import { mockProjects } from "@/shared/constants/mock-projects";

export function ProjectsSection() {
  return (
    <section className="py-16 md:py-24 bg-white">
      <div className="container">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-10">
          <SectionHeader
            title="Наши проекты"
            description="Государственные программы содействия занятости и профессионального развития"
          />
          <Button asChild variant="outline">
            <Link href="/projects">
              Все проекты
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
          {mockProjects.map((project, index) => (
            <ProjectCard key={project.id} project={project} index={index} />
          ))}
        </div>
      </div>
    </section>
  );
}

// components/widgets/ProjectsSection.vue
<script setup lang="ts">
import { ArrowRight } from "lucide-vue-next";
import { mockProjects } from "@/shared/constants/mock-projects";

// Временная заглушка для карточки проекта
const ProjectCardStub = {
  props: ['project', 'index'],
  template: `
    <div class="group rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all duration-300 hover:shadow-lg">
      <h3 class="text-lg font-semibold text-[#0A1628] mb-2">{{ project.title }}</h3>
      <p class="text-sm text-[#3A5070] mb-4">{{ project.description }}</p>
      <div class="text-xs font-medium text-[#0050AA]">Подробнее →</div>
    </div>
  `
};
</script>

<template>
  <section class="py-16 md:py-24 bg-white">
    <div class="container">
      <div class="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-10">
        <SectionHeader
          title="Наши проекты"
          description="Государственные программы содействия занятости и профессионального развития"
        />
        <Button as-child variant="outline">
          <NuxtLink to="/projects">
            Все проекты
            <ArrowRight class="h-4 w-4" />
          </NuxtLink>
        </Button>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
        <component 
          :is="ProjectCardStub" 
          v-for="(project, index) in mockProjects" 
          :key="project.id" 
          :project="project" 
          :index="index" 
        />
      </div>
    </div>
  </section>
</template>
